<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.22">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>index</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-cd7454b418030687c631a6a7286fbe16.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Garbage Can Regression Challenge</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="garbage-can-regression-challenge" class="level1">
<h1>Garbage Can Regression Challenge</h1>
<p><strong>Choose R or Python and delete the other code chunk.</strong></p>
<section id="python-code" class="level2">
<h2 class="anchored" data-anchor-id="python-code">Python Code</h2>
<div id="874e2378" class="cell" data-execution_count="1">
<div class="cell-output cell-output-stdout">
<pre><code>    Stress  StressSurvey  Time  Anxiety
0        0             0   0.0     0.00
1        0             0   1.0     0.10
2        0             0   1.0     0.10
3        1             3   1.0     1.10
4        1             3   1.0     1.10
5        1             3   1.0     1.10
6        2             6   2.0     2.20
7        2             6   2.0     2.20
8        2             6   2.0     2.20
9        8             9   2.0     8.20
10       8             9   2.0     8.20
11       8             9   2.1     8.21
12      12            12   2.2    12.22
13      12            12   2.2    12.22
14      12            12   2.2    12.22</code></pre>
</div>
</div>
</section>
<section id="your-analysis" class="level2">
<h2 class="anchored" data-anchor-id="your-analysis">Your Analysis</h2>
<section id="bivariate-regression-anxiety-on-stresssurvey" class="level3">
<h3 class="anchored" data-anchor-id="bivariate-regression-anxiety-on-stresssurvey">Bivariate Regression: Anxiety on StressSurvey</h3>
<div id="b9092a42" class="cell" data-execution_count="2">
<div class="cell-output cell-output-stdout">
<pre><code>Regression Results:
Intercept (beta0): -1.5240
Slope (beta1): 1.0470
R-squared: 0.9011

Comparison to True Relationship:
True relationship: Anxiety = Stress + 0.1 × Time
True coefficient of Stress: 1.0
Estimated coefficient of StressSurvey: 1.0470
Difference from true: 0.0470</code></pre>
</div>
</div>
</section>
<section id="question-1-what-are-the-estimated-coefficients-how-do-they-compare-to-the-true-coefficients" class="level3">
<h3 class="anchored" data-anchor-id="question-1-what-are-the-estimated-coefficients-how-do-they-compare-to-the-true-coefficients">Question 1: What are the estimated coefficients? How do they compare to the true coefficients</h3>
<p>The estimated coefficients are 1.0470 for the StressSurvey (slope) and -1.5240 for the intercept. The true coefficients are 1.0 for the stress, 0 for the intercept, and 0.1 for the Time. The difference from the true coefficients is 0.0470 for StressSurvey and -1.5240 for the intercept. This tells me that the StressSurvey is a good proxy for the true Stress variable, but the intercept is not a good proxy for the true intercept as it is not 0.</p>
</section>
<section id="scatter-plot-with-regression-line" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plot-with-regression-line">Scatter Plot with Regression Line</h3>
<div id="831fb057" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-1.png" width="951" height="566" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Fit Analysis:
R-squared: 0.9011 (90.1% of variance explained)
Root Mean Square Error: 1.4716
Mean Absolute Error: 1.2300

Potential Issues Analysis:
1. Clustering: Notice the data points cluster at specific StressSurvey values (0, 3, 6, 9, 12)
2. Limited variability: Most variation occurs at discrete levels rather than continuous
3. Perfect linear pattern: The relationship appears artificially perfect</code></pre>
</div>
</div>
</section>
<section id="question-2-commentary-on-fit-and-potential-issues" class="level3">
<h3 class="anchored" data-anchor-id="question-2-commentary-on-fit-and-potential-issues">Question 2: Commentary on Fit and Potential Issues</h3>
<p><strong>Model Fit Assessment:</strong></p>
<p>The fit is pretty good with a R-squared of 90.11%. The root mean square error is 0.7828 and the mean absolute error is 0.6241. This tells me that the model is a good fit for the data. The data points are scattered around the regression line and the residuals are not clustered at any specific time value. This is a good sign as it suggests that the model is a good fit for the data.</p>
<hr>
</section>
<section id="bivariate-regression-anxiety-on-time" class="level3">
<h3 class="anchored" data-anchor-id="bivariate-regression-anxiety-on-time">Bivariate Regression: Anxiety on Time</h3>
<div id="8afb4945" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>Regression Results (Anxiety on Time):
Intercept (beta0): -3.6801
Slope (beta1): 5.3406
R-squared: 0.5630

Comparison to True Relationship:
True relationship: Anxiety = Stress + 0.1 × Time
True coefficient of Time: 0.1
Estimated coefficient of Time: 5.3406
Difference from true: 5.2406</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-5-output-2.png" width="951" height="566" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Fit Analysis:
R-squared: 0.5630 (56.3% of variance explained)
Root Mean Square Error: 3.0933
Mean Absolute Error: 2.5607</code></pre>
</div>
</div>
</section>
<section id="question-3-what-are-the-estimated-coefficients-how-do-they-compare-to-the-true-relationship" class="level3">
<h3 class="anchored" data-anchor-id="question-3-what-are-the-estimated-coefficients-how-do-they-compare-to-the-true-relationship">Question 3: What are the estimated coefficients? How do they compare to the true relationship?</h3>
<p>The estimated coefficients are 5.3406 for the time and -3.6801 for the intercept. The true coefficients are 0.1 for the time and 0 for the intercept. The difference from the true coefficients is 5.2406 for the time and -3.6801 for the intercept. The time coefficient is much larger than the true value, which means that the model overestimates the effect of time on anxiety.</p>
</section>
<section id="scatter-plot-with-regression-line-time-vs-anxiety" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plot-with-regression-line-time-vs-anxiety">Scatter Plot with Regression Line: Time vs Anxiety</h3>
<div id="54e56b81" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-6-output-1.png" width="951" height="566" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Fit Analysis:
R-squared: 0.5630 (56.3% of variance explained)
Root Mean Square Error: 3.0933
Mean Absolute Error: 2.5607

Potential Issues Analysis:
1. Clustering: Notice the data points cluster at specific Time values (0, 1, 2, 2.1, 2.2)
2. Limited variability: Most variation occurs at discrete levels rather than continuous
3. Poor fit: R-squared of 56.3% indicates Time alone is not a strong predictor
4. Large residuals: Substantial prediction errors throughout the range</code></pre>
</div>
</div>
</section>
<section id="question-4-commentary-on-fit-and-potential-issues" class="level3">
<h3 class="anchored" data-anchor-id="question-4-commentary-on-fit-and-potential-issues">Question 4: Commentary on Fit and Potential Issues</h3>
<p>The fit is not very good with a R-squared of 56.3%. The root mean square error is 3.0933 and the mean absolute error is 2.5607. This tells me that the model is not a good fit for the data. The data points are clustered at specific Time values (0, 1, 2, 2.1, 2.2) and the residuals are not random. This is a bad sign as it suggests that the model is not a good fit for the data. Time by itself is not a good predictor of anxiety.</p>
<hr>
</section>
<section id="multiple-regression-anxiety-on-stresssurvey-and-time" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-anxiety-on-stresssurvey-and-time">Multiple Regression: Anxiety on StressSurvey and Time</h3>
<div id="87ce1253" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>Multiple Regression Results:
Intercept (β₀): 0.5888
StressSurvey coefficient (β₁): 1.4269
Time coefficient (β₂): -2.7799
R-squared: 0.9350

Comparison to True Relationship:
True relationship: Anxiety = Stress + 0.1 × Time
True coefficient of Stress: 1.0
True coefficient of Time: 0.1

Estimated StressSurvey coefficient: 1.4269
Difference from true Stress: 0.4269

Estimated Time coefficient: -2.7799
Difference from true Time: 2.8799

Fit Analysis:
R-squared: 0.9350 (93.5% of variance explained)
Root Mean Square Error: 1.1930
Mean Absolute Error: 1.0305</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-7-output-2.png" width="738" height="758" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="question-5-what-are-the-estimated-coefficients-how-do-they-compare-to-the-true-relationship" class="level3">
<h3 class="anchored" data-anchor-id="question-5-what-are-the-estimated-coefficients-how-do-they-compare-to-the-true-relationship">Question 5: What are the estimated coefficients? How do they compare to the true relationship?</h3>
<p>The estimated coefficients are 0.588 for the intercept, 1.4269 for StressSurvey, and -2.7799. The true coefficients are 0 for the intercept, 1 for the stress, and .1 for the time. Time is concerning as it is not close to the true value. The time coefficient suggest that for every 1 unit of time, the anxiety decreases by 2.7799 units. This is quite different from the true relationship.</p>
<hr>
</section>
<section id="multiple-regression-anxiety-on-true-stress-and-time" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-anxiety-on-true-stress-and-time">Multiple Regression: Anxiety on TRUE Stress and Time</h3>
<div id="a53450ca" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code>Multiple Regression Results (TRUE Variables):
Intercept (β₀): 0.0000
Stress coefficient (β₁): 1.0000
Time coefficient (β₂): 0.1000
R-squared: 1.0000

Comparison to True Relationship:
True relationship: Anxiety = Stress + 0.1 × Time
True coefficient of Stress: 1.0
True coefficient of Time: 0.1
True intercept: 0.0

Estimated Stress coefficient: 1.0000
Difference from true Stress: 0.0000

Estimated Time coefficient: 0.1000
Difference from true Time: 0.0000

Estimated intercept: 0.0000
Difference from true intercept: 0.0000

Fit Analysis:
R-squared: 1.0000 (100.0% of variance explained)
Root Mean Square Error: 0.0000
Mean Absolute Error: 0.0000</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-8-output-2.png" width="722" height="759" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="questions-to-answer-for-85-grade-on-challenge" class="level3">
<h3 class="anchored" data-anchor-id="questions-to-answer-for-85-grade-on-challenge">Questions to answer for 85% Grade on Challenge:</h3>
</section>
<section id="question-4-what-are-the-estimated-coefficients-how-do-they-compare-to-the-true-relationship" class="level3">
<h3 class="anchored" data-anchor-id="question-4-what-are-the-estimated-coefficients-how-do-they-compare-to-the-true-relationship">Question 4: What are the estimated coefficients? How do they compare to the true relationship?</h3>
<p>The estimated coefficients are 0 for the intercept, 1 for the stress, and .1 for the time. These are the same as the true coefficients. The true relationship is Anxiety = Stress + 0.1 × Time. These estimated coefficents demonstrate that the model is a perfect fit for the data. Using true stress rather than stress survey results in a perfect fit.</p>
<hr>
</section>
</section>
<section id="comparison-of-multiple-regression-models-with-statistical-significance-testing" class="level2">
<h2 class="anchored" data-anchor-id="comparison-of-multiple-regression-models-with-statistical-significance-testing">Comparison of Multiple Regression Models with Statistical Significance Testing</h2>
<div id="57f79cf6" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>================================================================================
MODEL 1: Anxiety ~ StressSurvey + Time
================================================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.935
Model:                            OLS   Adj. R-squared:                  0.924
Method:                 Least Squares   F-statistic:                     86.32
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           7.54e-08
Time:                        22:03:46   Log-Likelihood:                -23.931
No. Observations:                  15   AIC:                             53.86
Df Residuals:                      12   BIC:                             55.99
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.5888      1.034      0.569      0.580      -1.664       2.841
StressSurvey     1.4269      0.172      8.287      0.000       1.052       1.802
Time            -2.7799      1.111     -2.502      0.028      -5.201      -0.359
==============================================================================
Omnibus:                        1.255   Durbin-Watson:                   1.043
Prob(Omnibus):                  0.534   Jarque-Bera (JB):                1.051
Skew:                           0.546   Prob(JB):                        0.591
Kurtosis:                       2.302   Cond. No.                         31.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.


================================================================================
MODEL 2: Anxiety ~ TRUE Stress + Time
================================================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 8.600e+31
Date:                Mon, 13 Oct 2025   Prob (F-statistic):          1.15e-187
Time:                        22:03:46   Log-Likelihood:                 493.62
No. Observations:                  15   AIC:                            -981.2
Df Residuals:                      12   BIC:                            -979.1
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        1.11e-16   1.02e-15      0.109      0.915   -2.11e-15    2.34e-15
Stress         1.0000   1.15e-16   8.67e+15      0.000       1.000       1.000
Time           0.1000   8.12e-16   1.23e+14      0.000       0.100       0.100
==============================================================================
Omnibus:                        3.041   Durbin-Watson:                   0.639
Prob(Omnibus):                  0.219   Jarque-Bera (JB):                1.362
Skew:                           0.357   Prob(JB):                        0.506
Kurtosis:                       1.709   Cond. No.                         23.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<section id="detailed-comparison-analysis" class="level3">
<h3 class="anchored" data-anchor-id="detailed-comparison-analysis">Detailed Comparison Analysis</h3>
<div id="dd04e595" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>
====================================================================================================
COMPREHENSIVE MODEL COMPARISON
====================================================================================================
                Metric Model 1 (StressSurvey)               Model 2 (TRUE Stress) True Values
             R-squared               0.935005                            1.000000      1.0000
    Adjusted R-squared               0.924173                            1.000000      1.0000
 Intercept Coefficient               0.588758                            0.000000      0.0000
     Intercept p-value               0.579542                            0.915218         N/A
Intercept Significant?                     No                                  No         N/A
    Stress Coefficient               1.426926                            1.000000      1.0000
        Stress p-value               0.000003                        0.0000000000         N/A
   Stress Significant?                    Yes                                 Yes         N/A
      Time Coefficient              -2.779944                            0.100000      0.1000
          Time p-value               0.027816                        0.0000000000         N/A
     Time Significant?                    Yes                                 Yes         N/A
                  RMSE               1.333799                            0.000000      0.0000
           F-statistic                  86.32 86001455036830697088638659854336.00         N/A
   F-statistic p-value               0.000000                        0.0000000000         N/A
====================================================================================================

================================================================================
KEY INSIGHTS FROM COMPARISON
================================================================================

1. R-SQUARED COMPARISON:
   Model 1 (StressSurvey): 0.935005 (93.50% variance explained)
   Model 2 (TRUE Stress):  1.0000000000 (100.00% variance explained)
   → Model 2 achieves essentially perfect fit (R² ≈ 1.0000)

2. COEFFICIENT INTERPRETATIONS:

   MODEL 1 (StressSurvey + Time):
   • Intercept: 0.588758
     → For every 1-unit increase in StressSurvey, Anxiety increases by 1.426926
   • StressSurvey: 1.426926
     → Very close to true value of 1.0 (difference: 0.426926)
   • Time: -2.779944
     → Close to true value of 0.1 (difference: 2.879944)

   MODEL 2 (TRUE Stress + Time):
   • Intercept: 0.0000000000
     → Essentially 0, matching true value perfectly
   • Stress: 1.0000000000
     → Essentially 1.0, matching true value perfectly
   • Time: 0.1000000000
     → Essentially 0.1, matching true value perfectly

3. STATISTICAL SIGNIFICANCE (α = 0.05):

   MODEL 1:
   • Intercept: p = 0.579542 → NOT SIGNIFICANT
   • StressSurvey: p = 0.000003 → SIGNIFICANT
   • Time: p = 0.027816 → SIGNIFICANT
   → All coefficients significant? False

   MODEL 2:
   • Intercept: p = 0.9152184466 → NOT SIGNIFICANT
   • Stress: p = 0.0000000000 → SIGNIFICANT
   • Time: p = 0.0000000000 → SIGNIFICANT
   → All coefficients significant? False</code></pre>
</div>
</div>
</section>
<section id="question-5-compare-r-squared-values-and-coefficient-interpretations-between-the-two-models.-do-both-models-show-statistical-significance-in-all-coefficient-estimates-what-does-this-tell-you-about-real-world-implications-of-multiple-regression-results" class="level3">
<h3 class="anchored" data-anchor-id="question-5-compare-r-squared-values-and-coefficient-interpretations-between-the-two-models.-do-both-models-show-statistical-significance-in-all-coefficient-estimates-what-does-this-tell-you-about-real-world-implications-of-multiple-regression-results">Question 5: Compare R-squared values and coefficient interpretations between the two models. Do both models show statistical significance in all coefficient estimates? What does this tell you about real-world implications of multiple regression results?</h3>
<p><strong>R-squared Comparison:</strong></p>
<p>Model 1 (StressSurvey + Time) achieves an R² of approximately 0.935, explaining 93.5% of the variance in Anxiety. Model 2 (TRUE Stress + Time) achieves an R² of 1.0000. The minimal difference between them shows that StressSurvey is a good proxy for the true Stress variable.</p>
<p><strong>Coefficient Interpretations:</strong></p>
<p>The model involving StressSurvey and Time had a coefficient of 1.4269 for the StressSurvey and -2.7799 for the time. The model involving true stress and time had a coefficient of 1 for the stress and 0.1 for the time. The model involving true stress and time is a much better fit. In model 1,StressSurvey overpredicts the true anxiety level and time underpredicts the true anxiety level. Model 2 is much more accurate because it uses the true Stress variable rather than the survey proxy.</p>
<p><strong>Looking at the p-values from the statistical tests:</strong></p>
<p><strong>Model 1:</strong> The results show that the StressSurvey and Time coefficients are highly statistically significant (p &lt; 0.001), but the intercept’s significance depends on the specific p-value calculated. When the intercept is very close to 0, it may not be statistically different from 0.</p>
<p><strong>Model 2:</strong> All coefficients (Stress and Time) are extremely statistically significant (p ≈ 0), indicating perfect estimation of the true relationship. The intercept, being essentially 0, may not be statistically significant, which actually makes sense—it’s not significantly different from its true value of 0.</p>
<p>Time spent on social media is not a good predictor of anxiety levels by itself since it had a R-squared of 56.3% and a coefficient of 5.3406. Once we ran multiple regressions with both stress and StressSurvey, the model become much more accurate. The real-world implications learned from these results is to be careful with adding in variables in multiple regression since it can lead to overfitting and misleading conclusions.</p>
</section>
<section id="question-6-reflect-on-real-world-implications" class="level3">
<h3 class="anchored" data-anchor-id="question-6-reflect-on-real-world-implications">Question 6: Reflect on Real-World Implications</h3>
<p>For the first model, a headline could be “Social Media is Therapeutic!”. This model shows that the more time spent on social media, the lower the anxiety level as the coefficient is -2.7799. However, the model is not capturing the true relationship as StressSurvey is not the true Stress variable and is throwing off the results. For Model 2, a headline could be “Get off Social Media!”. This model shows that the more time spent on social media, the higher the anxiety level as the coefficient for time is 0.1. A typical parent will believe the second headline as it plays into the parent’s belief that social media is harmful to their children. As for Facebook, Instagram, and TikTok executives, they will likely believe the first headline as it plays into their belief that social media is beneficial to their users and can actually reduce anxiety.</p>
</section>
<section id="question-7-avoiding-misleading-statistical-significance" class="level3">
<h3 class="anchored" data-anchor-id="question-7-avoiding-misleading-statistical-significance">Question 7: Avoiding Misleading Statistical Significance:</h3>
<hr>
</section>
</section>
<section id="sample-splitting-analysis-high-stress-regime" class="level2">
<h2 class="anchored" data-anchor-id="sample-splitting-analysis-high-stress-regime">Sample Splitting Analysis: High Stress Regime</h2>
<section id="data-exploration-identifying-statistical-regimes" class="level3">
<h3 class="anchored" data-anchor-id="data-exploration-identifying-statistical-regimes">Data Exploration: Identifying Statistical Regimes</h3>
<div id="82ab10d2" class="cell" data-execution_count="10">
<div class="cell-output cell-output-stdout">
<pre><code>================================================================================
DATA EXPLORATION: IDENTIFYING STATISTICAL REGIMES
================================================================================

1. STRESS LEVELS IN THE DATA:
Unique Stress values: [0, 1, 2, 8, 12]

2. TIME PATTERNS BY STRESS LEVEL:
Stress 0: Time values = [0. 1. 1.]
Stress 1: Time values = [1. 1. 1.]
Stress 2: Time values = [2. 2. 2.]
Stress 8: Time values = [2.  2.  2.1]
Stress 12: Time values = [2.2 2.2 2.2]

3. ANXIETY VALUES BY STRESS LEVEL:
Stress 0: Anxiety values = [0.  0.1 0.1]
Stress 1: Anxiety values = [1.1 1.1 1.1]
Stress 2: Anxiety values = [2.2 2.2 2.2]
Stress 8: Anxiety values = [8.2  8.2  8.21]
Stress 12: Anxiety values = [12.22 12.22 12.22]

4. IDENTIFYING NATURAL BREAKS:
Looking at the data, we can identify two distinct regimes:
- LOW STRESS REGIME: Stress = 0, 1, 2 (Time values: 0, 1, 2)
- HIGH STRESS REGIME: Stress = 8, 12 (Time values: 2, 2.1, 2.2)

This split makes theoretical sense: low vs. high stress environments</code></pre>
</div>
</div>
</section>
<section id="choosing-a-meaningful-subset" class="level3">
<h3 class="anchored" data-anchor-id="choosing-a-meaningful-subset">Choosing a Meaningful Subset</h3>
<div id="30b76f31" class="cell" data-execution_count="11">
<div class="cell-output cell-output-stdout">
<pre><code>================================================================================
SUBSET ANALYSIS: HIGH STRESS REGIME
================================================================================

High Stress Subset (Stress &gt;= 8):
Number of observations: 6

Data:
    Stress  StressSurvey  Time  Anxiety
9        8             9   2.0     8.20
10       8             9   2.0     8.20
11       8             9   2.1     8.21
12      12            12   2.2    12.22
13      12            12   2.2    12.22
14      12            12   2.2    12.22

Why this subset?
1. Theoretically meaningful: High stress environments behave differently
2. Sufficient sample size: 6 observations
3. Clear regime separation: Stress levels 8 and 12 vs. 0, 1, 2
4. Time variation within regime: 2.0, 2.1, 2.2</code></pre>
</div>
</div>
</section>
<section id="graphical-diagnostics-for-the-subset" class="level3">
<h3 class="anchored" data-anchor-id="graphical-diagnostics-for-the-subset">Graphical Diagnostics for the Subset</h3>
<div id="85534e6a" class="cell" data-execution_count="12">
<div class="cell-output cell-output-stdout">
<pre><code>================================================================================
GRAPHICAL DIAGNOSTICS FOR HIGH STRESS SUBSET
================================================================================</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-13-output-2.png" width="1430" height="1142" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Graphical Analysis:
1. StressSurvey vs Anxiety: Clear linear relationship
2. Time vs Anxiety: Limited variation, but clear pattern
3. TRUE Stress vs Anxiety: Perfect linear relationship
4. 3D view: Shows both variables working together

Key insight: In high stress environments, both StressSurvey and Time show
clear linear relationships with Anxiety, supporting the multiple regression approach.</code></pre>
</div>
</div>
</section>
<section id="multiple-regression-on-the-subset" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-on-the-subset">Multiple Regression on the Subset</h3>
<div id="9e36272e" class="cell" data-execution_count="13">
<div class="cell-output cell-output-stdout">
<pre><code>================================================================================
MULTIPLE REGRESSION: HIGH STRESS SUBSET
================================================================================
REGRESSION RESULTS FOR HIGH STRESS SUBSET:
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 3.760e+28
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           2.52e-43
Time:                        22:03:48   Log-Likelihood:                 183.48
No. Observations:                   6   AIC:                            -361.0
Df Residuals:                       3   BIC:                            -361.6
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -4.0000   3.41e-13  -1.17e+13      0.000      -4.000      -4.000
StressSurvey     1.3333   1.31e-14   1.01e+14      0.000       1.333       1.333
Time             0.1000    2.2e-13   4.55e+11      0.000       0.100       0.100
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.029
Prob(Omnibus):                    nan   Jarque-Bera (JB):                1.062
Skew:                           0.707   Prob(JB):                        0.588
Kurtosis:                       1.500   Cond. No.                         600.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

============================================================
COMPARISON WITH TRUE RELATIONSHIP
============================================================
True relationship: Anxiety = Stress + 0.1 × Time
Estimated relationship: Anxiety = -4.000000 + 1.333333 × StressSurvey + 0.100000 × Time

Predictions comparison:
True predictions: 9      8.20
10     8.20
11     8.21
12    12.22
13    12.22
14    12.22
dtype: float64
Model predictions: [ 8.2   8.2   8.21 12.22 12.22 12.22]
Difference (MAE): 0.000000

Statistical Significance (α = 0.05):
Intercept: p = 0.000000 → SIGNIFICANT
StressSurvey: p = 0.000000 → SIGNIFICANT
Time: p = 0.000000 → SIGNIFICANT
All coefficients significant? True</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>C:\Users\willi\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\stats\stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "</code></pre>
</div>
</div>
</section>
<section id="comparison-subset-vs.-full-sample" class="level3">
<h3 class="anchored" data-anchor-id="comparison-subset-vs.-full-sample">Comparison: Subset vs.&nbsp;Full Sample</h3>
<div id="ce412868" class="cell" data-execution_count="14">
<div class="cell-output cell-output-stdout">
<pre><code>================================================================================
SUBSET vs. FULL SAMPLE COMPARISON
================================================================================
                 Metric Full Sample High Stress Subset
            Sample Size          15                  6
              R-squared    0.935005           1.000000
              Intercept    0.588758          -4.000000
     StressSurvey Coeff    1.426926           1.333333
             Time Coeff   -2.779944           0.100000
All Coeffs Significant?       False               True
     MAE vs True Values    1.030507           0.000000

============================================================
KEY INSIGHTS FROM SUBSET ANALYSIS
============================================================

1. SAMPLE SIZE IMPACT:
   Full sample: 15 observations
   Subset: 6 observations
   → Smaller sample reduces statistical power

2. MODEL PERFORMANCE:
   Full sample R²: 0.935005
   Subset R²: 1.000000
   → Both achieve excellent fit, but full sample is more robust

3. COEFFICIENT STABILITY:
   Full sample StressSurvey coeff: 1.426926
   Subset StressSurvey coeff: 1.333333
   → Coefficients are very similar, suggesting stability across regimes

4. STATISTICAL SIGNIFICANCE:
   Full sample - all significant: False
   Subset - all significant: True
   → Both show statistical significance, but with different confidence levels</code></pre>
</div>
</div>
</section>
<section id="answer-to-question-7-subset-analysis-results" class="level3">
<h3 class="anchored" data-anchor-id="answer-to-question-7-subset-analysis-results">Answer to Question 7: Subset Analysis Results</h3>
<p><strong>Specific Subset Chosen:</strong> I chose the <strong>High Stress regime</strong> (Stress ≥ 8), which includes observations with Stress values of 8 and 12. This subset contains 6 observations with Time values ranging from 2.0 to 2.2.</p>
<p>I chose this subset because it is a meaningful subset as it is a high stress regime and it has a sufficient sample size as it has 6 observations. This subset is also clearly seperated from the low stress regime.</p>
<p><strong>Results Analysis:</strong></p>
<p>The subset model had a R-squared of 1 which is a perfect fit. The results are very close to the true relationship. All coefficients are also statistically significant. These results suggest in order to avoid misleading conclusions, you should subset the data so you can control for proxys properly as low stress individuals are not the same as high stress individuals. The low stress individuals averaged the results and gave the misleading answer that social media can decrease anxiety.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>